### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jacsmithyay** [QuoteNat/vein_miner#6] opened 2022-08-16 20:56 UTC
![Screenshot (229)](https://user-images.githubusercontent.com/87614082/184983525-2e746c95-ef29-49ad-af78-9878c4129409.png)

Game crashed when I tried to vein mine a acacia tree with a stone axe

**Comment by QuoteNat** [comment] 2022-08-17 00:10
Not entirely sure why but I believe this was caused by the default setting for the maximum number of nodes mineable at once not being set initially. This should be fixed once the next update gets published on contentdb.

**Comment by QuoteNat** [comment] 2022-08-19 20:57
Closing due to inactivity and because this issue should be resolved by #7.

**Closed as completed by QuoteNat** 2022-08-19 20:57 UTC
Labels: bug
